# Generated by Django 3.1.7 on 2021-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210406_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('12th', '12th'), ('11th', '11th'), ('10th', '10th'), ('9th', '9th'), ('8th', '8th')], max_length=100),
        ),
    ]
