# Generated by Django 3.1.7 on 2021-04-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210411_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
